

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.SwingConstants;
import javax.swing.Timer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author josehumbertoabrilgarcia
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
    private String codigo = "";
    Color gris = new Color (224,224,224);
    int seg = 0;
    boolean entro = false;
    boolean  cronometroActivo = true;
    
    
    public NewJFrame() {
       
        initComponents();
        
        //Dimension size = Toolkit. getDefaultToolkit(). getScreenSize();
        //this.setSize(Toolkit.getDefaultToolkit().getScreenSize().width, Toolkit.getDefaultToolkit().getScreenSize().height);       
        
        
        this.setSize(839, 480);
        Color verde = new Color (17,234,17);
        this.getContentPane().setBackground(verde);
        this.setLayout(null);
        this.setLocationRelativeTo(null);
        
        barra_logo.setSize(835, 67);
        barra_logo.setText("");
        barra_logo.setText("<html><img src='file:C:\\Users\\Yesica\\Desktop\\VerificadorDePrecios\\VerificadorDePrecios\\src\\main\\java\\img\\barra.png' width='835' height='67'>");
        Color verde_calro = new Color (146,239,146);
        barra_logo.setBackground(verde_calro);
        barra_logo.setLocation(0, 140);
        
        logo.setSize(211, 146); 
        logo.setText("<html><img src='file:C:\\Users\\Yesica\\Desktop\\VerificadorDePrecios\\VerificadorDePrecios\\src\\main\\java\\img\\loog.png' width='211' height='146'>");
        logo.setLocation(321, 99);
        
        barcode_imgproduc.setSize(214, 139); 
        barcode_imgproduc.setText("<html><img src='file:C:\\Users\\Yesica\\Desktop\\VerificadorDePrecios\\VerificadorDePrecios\\src\\main\\java\\barcode-scan.gif' width='214' height='139'>");
        barcode_imgproduc.setLocation(321, 299);
        
        bienvenida_precio.setSize(281, 57); 
        bienvenida_precio.setLocation(321, 44);
        
        inst_disp.setSize(728, 38);
        inst_disp.setLocation(150, 252);
      
        desc.setVisible(false);
        desc.setSize(280, 144);
        desc.setBackground(gris);
        desc.setLocation(142, 231);
        
        men_noen.setVisible(false);
        men_noen.setSize(578, 200);
        men_noen.setText("<html><div style='text-align: center;'>El artículo que usted está buscando <br> no se ha encontrado <br> por favor pase a servicio al cliente.</div> </html>");
        men_noen.setLocation(200, 20);
        
        noencontrado.setVisible(false);
        noencontrado.setSize(355, 267);
        noencontrado.setText("<html><img src='file:C:\\Users\\Yesica\\Desktop\\VerificadorDePrecios\\VerificadorDePrecios\\src\\main\\java\\img\\noencontrado.png' width='355' height='267'>");
        noencontrado.setLocation(250, 188);
        
        nombre.setVisible(false);
        nombre.setSize(300, 44);
        nombre.setLocation(142, 54);

       
        
        //jLabel4.setLocation(this.getWidth()/2 - jLabel4.getWidth()/2 , jLabel3.getLocation().y + jLabel3.getHeight() + 10);
     
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barcode_imgproduc = new javax.swing.JLabel();
        bienvenida_precio = new javax.swing.JLabel();
        inst_disp = new javax.swing.JLabel();
        noencontrado = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        barra_logo = new javax.swing.JLabel();
        desc = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        men_noen = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(17, 234, 17));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(839, 480));
        setSize(new java.awt.Dimension(839, 480));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(null);

        barcode_imgproduc.setText("jLabel4");
        barcode_imgproduc.setPreferredSize(new java.awt.Dimension(120, 120));
        getContentPane().add(barcode_imgproduc);
        barcode_imgproduc.setBounds(420, 350, 80, 70);

        bienvenida_precio.setBackground(new java.awt.Color(224, 224, 224));
        bienvenida_precio.setFont(new java.awt.Font("Bodoni Bk BT", 0, 36)); // NOI18N
        bienvenida_precio.setText("Bienvenido a");
        bienvenida_precio.setAlignmentX(286.0F);
        bienvenida_precio.setAlignmentY(44.0F);
        getContentPane().add(bienvenida_precio);
        bienvenida_precio.setBounds(330, 80, 185, 43);

        inst_disp.setFont(new java.awt.Font("Bodoni Bk BT", 0, 24)); // NOI18N
        inst_disp.setText("Por favor pase el código de barras pordebajo del scanner");
        inst_disp.setAlignmentX(52.0F);
        inst_disp.setAlignmentY(252.0F);
        getContentPane().add(inst_disp);
        inst_disp.setBounds(180, 210, 537, 29);

        noencontrado.setText("jLabel3");
        noencontrado.setPreferredSize(new java.awt.Dimension(305, 165));
        getContentPane().add(noencontrado);
        noencontrado.setBounds(330, 350, 60, 60);

        logo.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        logo.setText("logo");
        getContentPane().add(logo);
        logo.setBounds(280, 290, 120, 32);

        barra_logo.setBackground(new java.awt.Color(146, 239, 146));
        barra_logo.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        barra_logo.setText("barra");
        getContentPane().add(barra_logo);
        barra_logo.setBounds(580, 140, 59, 32);

        desc.setBackground(new java.awt.Color(224, 224, 224));
        desc.setFont(new java.awt.Font("Bodoni Bk BT", 0, 30)); // NOI18N
        desc.setText("desc");
        getContentPane().add(desc);
        desc.setBounds(180, 280, 60, 32);

        nombre.setFont(new java.awt.Font("Bodoni Bk BT", 1, 28)); // NOI18N
        nombre.setText("nombre");
        getContentPane().add(nombre);
        nombre.setBounds(70, 270, 100, 60);

        men_noen.setFont(new java.awt.Font("Bodoni Bk BT", 0, 30)); // NOI18N
        men_noen.setText("jLabel3");
        men_noen.setPreferredSize(new java.awt.Dimension(305, 165));
        getContentPane().add(men_noen);
        men_noen.setBounds(610, 330, 60, 60);

        fondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yesica\\Desktop\\VerificadorDePrecios\\VerificadorDePrecios\\src\\main\\java\\img\\fondo.png")); // NOI18N
        fondo.setText("jLabel3");
        fondo.setPreferredSize(new java.awt.Dimension(305, 165));
        getContentPane().add(fondo);
        fondo.setBounds(0, 0, 840, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(null, evt.getKeyCode());
        
        if (evt.getKeyCode()!= 10) {
            codigo += evt.getKeyChar();
        }else{
            
            try{
                Connection con = null;
                Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/verificador_de_precios","root","");
                Statement stmt = con.createStatement();
                ResultSet rs = stmt.executeQuery("SELECT * FROM productos WHERE producto_codigo ="+codigo+";");
                
                if (rs.next()) {
                    //JOptionPane.showMessageDialog(null, rs.getString(2));
                    barra_logo.setVisible(false);
                    men_noen.setVisible(false);
                    noencontrado.setVisible(false);
                    
                    logo.setSize(101, 71); 
                    logo.setText("<html><img src='file:C:\\Users\\Yesica\\Desktop\\VerificadorDePrecios\\VerificadorDePrecios\\src\\main\\java\\img\\loog.png' width='101' height='71'>");
                    logo.setLocation(691, 39);
                    logo.setVisible(true);
                    
                    nombre.setText(rs.getString(2));
                    nombre.setVisible(true);
                    
                    bienvenida_precio.setSize(149, 56);
                    bienvenida_precio.setText("<html> $"+rs.getString(4)+"</html>");
                    bienvenida_precio.setHorizontalAlignment(SwingConstants.CENTER);
                    bienvenida_precio.setVerticalAlignment(SwingConstants.CENTER);
                    bienvenida_precio.setOpaque(true);
                    bienvenida_precio.setBackground(gris);
                    bienvenida_precio.setLocation(200, 151);
                    bienvenida_precio.setVisible(true);
                    
                    //desc.setText("<html>Nombre: "+rs.getString(2)+"<br>Precio:"+rs.getString(4)+"<br>Cantidad:"+rs.getString(3));
                    desc.setText("<html>"+rs.getString(6)+"</html>");
                    desc.setHorizontalAlignment(SwingConstants.CENTER);
                    desc.setVerticalAlignment(SwingConstants.CENTER);
                    desc.setOpaque(true);
                    desc.setBackground(gris);
                    desc.setVisible(true);
            
                    barcode_imgproduc.setSize(256,231);
                    barcode_imgproduc.setLocation(514, 128);
                    barcode_imgproduc.setText("<html><img src='file:"+rs.getString(5)+"' width='256' height='231'>");
                    barcode_imgproduc.setVisible(true);
                    
                    inst_disp.setSize(323, 38);
                    inst_disp.setText("<html> Disponible en surcursal:"+rs.getString(3));
                    inst_disp.setLocation(244, 400);
                    inst_disp.setVisible(true);
                    
                    //tem_enc.run();
                    tiempo t = new tiempo();
                    //cronometroActivo = true;
                    
                    //t.cal();
//                    if (t.terminado) {
//                        c();
//                    }

                    //Thread.sleep(5000);
                    //c();
                    
                     
//                        try {
//                            Thread.sleep(5000);
//                        } catch (InterruptedException ex) {
//                            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
//                        }
//                        c();
                        
                    
                    
                }else{
                    barra_logo.setVisible(false);
                    logo.setVisible(false);
                    bienvenida_precio.setVisible(false);
                    barcode_imgproduc.setVisible(false);
                    inst_disp.setVisible(false);
                    nombre.setVisible(false);
                    desc.setVisible(false);
                    
                    men_noen.setVisible(true);
                    noencontrado.setVisible(true);  
                    
                    
                }
            }catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Ha ocurrido un error"+e.toString());
                
            }
            codigo = "";
        }
        
        if (evt.getKeyCode()== 8) {
            codigo = "";        
            try {
                Thread.sleep(5000);
            } catch (InterruptedException ex) {
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            c();
        }
    }//GEN-LAST:event_formKeyPressed

     void c (){
        barra_logo.setVisible(true);
        nombre.setVisible(false);
        desc.setVisible(false);

        men_noen.setVisible(false);
        noencontrado.setVisible(false);

        logo.setSize(211, 146); 
        logo.setText("<html><img src='file:C:\\Users\\Yesica\\Desktop\\VerificadorDePrecios\\VerificadorDePrecios\\src\\main\\java\\img\\loog.png' width='211' height='146'>");
        logo.setLocation(321, 99);
        logo.setVisible(true);

        bienvenida_precio.setSize(281, 57);
        bienvenida_precio.setText("Bienvenido a");
        bienvenida_precio.setOpaque(false);
        bienvenida_precio.setLocation(290, 44);
        bienvenida_precio.setVisible(true);

        inst_disp.setSize(728, 38);
        inst_disp.setText("Por favor pase el código de barras por debajo del scanner");
        inst_disp.setLocation(150, 252);
        inst_disp.setVisible(true);

        barcode_imgproduc.setSize(214, 139); 
        barcode_imgproduc.setText("<html><img src='file:C:\\Users\\Yesica\\Desktop\\VerificadorDePrecios\\VerificadorDePrecios\\src\\main\\java\\barcode-scan.gif' width='214' height='139'>");
        barcode_imgproduc.setLocation(321, 299);
        barcode_imgproduc.setVisible(true);
    }
    
     
     public void cronometro() {
        Integer  segundos = 0, milesimas = 0;
        //min es minutos, seg es segundos y mil es milesimas de segundo
        String min = "", seg = "", mil = "";
        try {
            //Mientras cronometroActivo sea verdadero entonces seguira
            //aumentando el tiempo
            while (cronometroActivo) {
                Thread.sleep(4);
                //Incrementamos 4 milesimas de segundo
                milesimas += 4;
                //Cuando llega a 1000 osea 1 segundo aumenta 1 segundo
                //y las milesimas de segundo de nuevo a 0
                if (milesimas == 1000) {
                    milesimas = 0;
                    segundos += 1;
                    if (segundos == 8) {
                        //cronometroActivo = false;
                        c();
                    }
                }
            }
        } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Ha ocurrido un error en cronometro: "+e.toString());
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel barcode_imgproduc;
    private javax.swing.JLabel barra_logo;
    private javax.swing.JLabel bienvenida_precio;
    private javax.swing.JLabel desc;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel inst_disp;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel men_noen;
    private javax.swing.JLabel noencontrado;
    private javax.swing.JLabel nombre;
    // End of variables declaration//GEN-END:variables
}
